<a href="https://colab.research.google.com/github/2303A52337/GENERATIVE_AI_2025/blob/main/GenAI_2303A52337_Week_No_1_Assignment_No_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1.Question**

**1. (1 ponto) Write Python code from scratch to find error metrics of deep learning model. Actual values and deep learning model predicted values are shown in Table 1. Also compare the resultswith the outcomes of libraries**

**YActual:[ 20 , 30 , 40 , 50 , 60]**     
**YPred: [20.5 , 30.3 , 40.2 , 50.6 , 60.7]**

**Tabela 1: YActual Vs. YPred**


#**Actual and predicted values**

In [ ]:
import numpy as np
y_actual = np.array([20, 30, 40, 50, 60])
y_pred = np.array([20.5, 30.3, 40.2, 50.6, 60.7])

# **Mean Absolute Error (MAE)**

In [ ]:
def mae(y_actual, y_pred):
  return np.mean(np.abs(y_actual - y_pred))
mae_result = mae(y_actual, y_pred)
print(f"Mean Absolute Error (MAE): {mae_result}")

Mean Absolute Error (MAE): 0.4600000000000016


#**Mean Squared Error (MSE)**

In [ ]:
def mse(y_actual, y_pred):
  return np.mean(np.square(y_actual - y_pred))
mse_result = mse(y_actual, y_pred)
print(f"Mean Squared Error (MSE): {mse_result}")

Mean Squared Error (MSE): 0.24600000000000147


# **Root Mean Squared Error (RMSE)**

In [ ]:
def rmse(y_actual, y_pred):
  return np.sqrt(mse(y_actual,y_pred))
rmse_result = rmse(y_actual, y_pred)
print(f"Root Mean Squared Error (RMSE): {rmse_result}")

Root Mean Squared Error (RMSE): 0.49598387070549127


# **Comparison with libraries (sklearn)**

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
mae_sklearn = mean_absolute_error(y_actual, y_pred)
mse_sklearn = mean_squared_error(y_actual, y_pred)
rmse_sklearn = np.sqrt(mse_sklearn)

print(f"\nComparison with scikit-learn:")
print(f"MAE (sklearn): {mae_sklearn}")
print(f"MSE (sklearn): {mse_sklearn}")
print(f"RMSE (sklearn): {rmse_sklearn}")


Comparison with scikit-learn:
MAE (sklearn): 0.4600000000000016
MSE (sklearn): 0.24600000000000147
RMSE (sklearn): 0.49598387070549127


# **Question 2**

**2. (1 ponto) Write python code from scratch to find evaluation metrics of deep learning model.Actual values and deep learning model predicted values are** **shown in Table 2. Also compare the results with outcome of libraries**

**YActual: [ 0 , 0 , 0 , 0 , 0 ]**

**YPred: [0 , 0  , 1 , 2 , 2 ]**

**Tabela 2: YActual Vs. YPred**


#**Actual and predicted values**

In [ ]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error
y_actual = np.array([0, 0, 0, 0, 0])
y_pred = np.array([0, 0, 1, 2, 2])

# **Mean Absolute Error (MAE)**

In [ ]:
def mae(y_actual, y_pred):
  return np.mean(np.abs(y_actual - y_pred))
mae_result = mae(y_actual, y_pred)
print(f"Mean Absolute Error (MAE): {mae_result}")

Mean Absolute Error (MAE): 1.0


#**Mean Squared Error (MSE)**

In [ ]:
def mse(y_actual, y_pred):
  return np.mean(np.square(y_actual - y_pred))
mse_result = mse(y_actual, y_pred)
print(f"Mean Squared Error (MSE): {mse_result}")

Mean Squared Error (MSE): 1.8


# **Root Mean Squared Error (RMSE)**

In [ ]:
def rmse(y_actual, y_pred):
  return np.sqrt(mse(y_actual, y_pred))
rmse_result = rmse(y_actual, y_pred)
print(f"Root Mean Squared Error (RMSE): {rmse_result}")

Root Mean Squared Error (RMSE): 1.3416407864998738


# **Comparison with libraries (sklearn)**

In [ ]:
mae_sklearn = mean_absolute_error(y_actual, y_pred)
mse_sklearn = mean_squared_error(y_actual, y_pred)
rmse_sklearn = np.sqrt(mse_sklearn)

print(f"\nComparison with scikit-learn:")
print(f"MAE (sklearn): {mae_sklearn}")
print(f"MSE (sklearn): {mse_sklearn}")
print(f"RMSE (sklearn): {rmse_sklearn}")


Comparison with scikit-learn:
MAE (sklearn): 1.0
MSE (sklearn): 1.8
RMSE (sklearn): 1.3416407864998738


# **Additional metrics relevant for classification(since the data seems binary)**

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix # Import confusion_matrix

accuracy = accuracy_score(y_actual, y_pred)
precision = precision_score(y_actual, y_pred, average='micro')
recall = recall_score(y_actual, y_pred, average='micro')
f1 = f1_score(y_actual, y_pred, average='micro')

print(f"\nClassification Metrics:")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")

conf_matrix = confusion_matrix(y_actual, y_pred) # Calculate the confusion matrix

print(f"\nConfusion Matrix:")
print(conf_matrix)


Classification Metrics:
Accuracy: 0.4
Precision: 0.4
Recall: 0.4
F1 Score: 0.4

Confusion Matrix:
[[2 1 2]
 [0 0 0]
 [0 0 0]]
